export interface userData {
  fullName?: string;
  fatherName?: string;
  email?: string;
  phoneNumber?: string;
  city?: string;
  province?: string;
  education?: string;
  course?: string;
  message?: string;
}

export const provinces = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Islamabad Capital Territory",
  "Gilgit-Baltistan",
  "Azad Jammu & Kashmir",
];

export const cities = [
  "Lahore",
  "Karachi",
  "Islamabad",
  "Faisalabad",
  "Rawalpindi",
  "Multan",
  "Peshawar",
  "Quetta",
  "Hyderabad",
  "Sialkot",
  "Gujranwala",
  "Bahawalpur",
  "Sargodha",
  "Sukkur",
  "Abbottabad",
  "Dera Ghazi Khan",
  "Mardan",
  "Kasur",
  "Sheikhupura",
  "Mirpur",
  "Gujrat",
  "Jhelum",
  "Rahim Yar Khan",
  "Okara",
  "Muzaffargarh",
  "Kohat",
  "Bannu",
  "Chakwal",
  "Khushab",
  "Nawabshah",
  "Tando Adam",
  "Larkana",
  "Jacobabad",
  "Thatta",
  "Nowshera",
  "Charsadda",
  "Mingora",
  "Chitral",
  "Gilgit",
  "Skardu",
  "Muzaffarabad",
  "Kotli",
  "Swabi",
  "Dadu",
  "Vehari",
  "Hafizabad",
  "Toba Tek Singh",
  "Jhang",
  "Bahawalnagar",
  "Layyah",
  "Shikarpur",
  "Mansehra",
  "Khanewal",
  "Ghotki",
  "Attock",
  "Lodhran",
  "Bhakkar",
  "Mianwali",
  "Sahiwal",
  "Pakpattan",
  "Kamoke",
  "Tando Allahyar",
  "Kamber",
  "Kharian",
  "Wazirabad",
  "Narowal",
  "Shangla",
  "Turbat",
  "Zhob",
  "Gwadar",
  "Khuzdar",
  "Jiwani",
];
